# Generated by Django 2.2.2 on 2019-07-03 09:45

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_auto_20190703_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.CharField(max_length=50, verbose_name=ecomapp.models.Cart),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=150, verbose_name='auth.User'),
        ),
    ]
