# Generated by Django 2.2.2 on 2019-07-01 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='connected_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
