# Generated by Django 2.2.2 on 2019-07-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_auto_20190701_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
