# Generated by Django 2.2.2 on 2019-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_auto_20190702_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='ecomapp.Product'),
        ),
    ]
