# Generated by Django 2.2.2 on 2019-07-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_auto_20190702_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.ManyToManyField(to='ecomapp.CartItem'),
        ),
    ]
