# Generated by Django 2.2.2 on 2019-07-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_auto_20190702_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
    ]
