# Generated by Django 2.2.2 on 2019-07-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0022_auto_20190702_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='cart',
        ),
    ]
