# Generated by Django 2.2.2 on 2019-07-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0025_auto_20190703_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='items',
        ),
    ]
