# Generated by Django 2.2.2 on 2019-07-12 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0028_auto_20190710_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amper',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
